// SPDX-License-Identifier: MIT
package dev.worldgennext.neoforge.compat;

import it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap;
import it.unimi.dsi.fastutil.longs.LongArrayList;
import it.unimi.dsi.fastutil.longs.LongOpenHashSet;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerChunkCache;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.TicketType;
import net.minecraft.world.level.ChunkPos;
import net.minecraft.world.level.chunk.ChunkAccess;
import net.minecraft.world.level.chunk.status.ChunkStatus;
import net.neoforged.fml.ModList;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.lang.reflect.InvocationHandler;
import java.lang.reflect.Method;
import java.lang.reflect.Proxy;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.IdentityHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.atomic.AtomicLong;
import java.util.function.Consumer;

/**
 * Sends Distant Horizons' chunk generation through the server's chunk system.
 *
 * <p>Distant Horizons builds distant terrain two ways: a rough surface generator that samples heights, and a
 * chunk generator of its own that runs outside the chunk system, one small tile (4x4 chunks) per worker
 * thread.  With this mod the chunk system is the faster source of chunks, so this class registers a world
 * generator override through Distant Horizons' API.  In "hybrid" mode the override wraps Distant Horizons'
 * own generator and only redirects its chunk requests; in "direct" mode it answers every request with
 * finished chunks itself.  In both, the tiles around a request are started early so that enough chunks are
 * in flight, and {@link DistantHorizonsHandover} keeps Distant Horizons from building them twice.</p>
 *
 * <p>The chunks are real: they are saved in the world like chunks generated by Distant Horizons'
 * INTERNAL_SERVER mode.  Distant Horizons is not a build dependency; everything goes through reflection and
 * a dynamic proxy, and nothing here runs unless the mod is installed.  Measurements and limits:
 * docs/evidence/comparison-distant-horizons.md.</p>
 */
public final class DistantHorizonsBridge {
    /**
     * "hybrid" (the default): Distant Horizons' own generator stays in charge, with its rough surface for far
     * terrain and its plan, and only its chunk generation is sent through the server's chunk system.
     * "direct": every request is answered with finished chunks, through its public API only; its rough surface
     * generator is then not used at all, so far terrain appears only as chunks are finished.
     * "off": Distant Horizons is left alone.
     */
    private static final String MODE = mode(System.getProperty("worldgennext.dh.mode", "hybrid"));
    public static final boolean ENABLED = !MODE.equals("off");
    private static final boolean HYBRID = MODE.equals("hybrid");
    /**
     * Most chunks started ahead of Distant Horizons' requests at one time; 0 turns that off.  Unless set, one
     * chunk per 4 MB of heap, at most 4,096: these are finished chunks waiting to be asked for.
     */
    private static final int AHEAD_WINDOW = Math.max(0, Integer.getInteger("worldgennext.dh.readAhead",
            (int) Math.min(4096, Runtime.getRuntime().maxMemory() / (4L << 20))));
    /** How far from a requested tile chunks are started ahead, in chunks. */
    private static final int AHEAD_REACH = Math.max(0, Integer.getInteger("worldgennext.dh.readAheadReach", 32));
    /** A chunk started ahead and not asked for within this time is let go. */
    private static final long AHEAD_EXPIRY_NANOS = 30_000_000_000L;
    private static final Logger LOG = LoggerFactory.getLogger("worldgennext");
    private static final TicketType<ChunkPos> TICKET =
            TicketType.create("worldgennext_dh", Comparator.comparingLong(ChunkPos::toLong));

    private static volatile Thread watcher;
    private static final AtomicLong CHUNKS = new AtomicLong();
    private static final AtomicLong AHEAD_USED = new AtomicLong();
    private static final AtomicLong REQUESTS = new AtomicLong();
    private static final AtomicLong REQUESTS_DONE = new AtomicLong();
    /** -Dworldgennext.dh.log=true writes the counters to the log every ten seconds. */
    private static final boolean PERIODIC_LOG = Boolean.getBoolean("worldgennext.dh.log");
    private static final AtomicLong AHEAD_EXPIRED = new AtomicLong();

    private DistantHorizonsBridge() {}

    private static String mode(String value) {
        String mode = value.trim().toLowerCase(Locale.ROOT);
        return mode.equals("direct") || mode.equals("off") ? mode : "hybrid";
    }

    public static boolean installed() {
        return ModList.get().isLoaded("distanthorizons");
    }

    /** Chunks handed to Distant Horizons since the server started. */
    public static long chunksProvided() {
        return CHUNKS.get();
    }

    /**
     * Registers the override for every server level Distant Horizons loads.  Distant Horizons chooses a level's
     * generator once, about half a second after it loads the level, so this starts before the levels exist and
     * looks often.
     */
    public static void serverStarting(MinecraftServer server) {
        if (!ENABLED || !installed()) return;
        CHUNKS.set(0);
        AHEAD_USED.set(0);
        REQUESTS.set(0);
        REQUESTS_DONE.set(0);
        AHEAD_EXPIRED.set(0);
        DistantHorizonsHandover.SKIPPED.set(0);
        Thread thread = new Thread(() -> watch(server), "worldgennext-dh-bridge");
        thread.setDaemon(true);
        watcher = thread;
        thread.start();
    }

    public static void serverStopping() {
        Thread thread = watcher;
        watcher = null;
        if (thread != null) thread.interrupt();
        DistantHorizonsHandover.serverStopping();
    }

    private static void watch(MinecraftServer server) {
        Set<Object> registered = Collections.newSetFromMap(new IdentityHashMap<>());
        List<Generator> generators = new ArrayList<>();
        long swept = System.nanoTime();
        int sweeps = 0;
        try {
            Class<?> delayed = Class.forName("com.seibel.distanthorizons.api.DhApi$Delayed");
            Class<?> api = Class.forName("com.seibel.distanthorizons.api.DhApi");
            Class<?> generatorType = Class.forName("com.seibel.distanthorizons.api.interfaces.override.worldGenerator.IDhApiWorldGenerator");
            Class<?> wrapperType = Class.forName("com.seibel.distanthorizons.api.interfaces.world.IDhApiLevelWrapper");
            Object register = api.getField("worldGenOverrides").get(null);
            Method registerOverride = register.getClass().getMethod("registerWorldGeneratorOverride", wrapperType, generatorType);
            Object injector = Class.forName("com.seibel.distanthorizons.coreapi.DependencyInjection.WorldGeneratorInjector")
                    .getField("INSTANCE").get(null);
            Method bound = injector.getClass().getMethod("get", wrapperType);
            if (HYBRID) {
                // Distant Horizons' own generator is not part of its API.  Without it there is nothing to wrap.
                try {
                    Class.forName("com.seibel.distanthorizons.core.generation.DhWorldGenerator")
                            .getConstructor(Class.forName("com.seibel.distanthorizons.core.level.IDhServerLevel"));
                    Class.forName("com.seibel.distanthorizons.core.wrapperInterfaces.world.ILevelWrapper").getMethod("getDhLevel");
                } catch (ReflectiveOperationException | LinkageError missing) {
                    LOG.warn("This version of Distant Horizons does not have the generator class this mod wraps ({}); it keeps"
                            + " using its own generator.  distant_horizons.generator = \"direct\" does not need that class.",
                            missing.toString());
                    return;
                }
            }
            DistantHorizonsHandover.prepare();
            long started = System.nanoTime();
            while (watcher == Thread.currentThread()) {
                Object worldProxy = delayed.getField("worldProxy").get(null);
                if (worldProxy != null && (boolean) worldProxy.getClass().getMethod("worldLoaded").invoke(worldProxy)) {
                    Iterable<?> wrappers = (Iterable<?>) worldProxy.getClass().getMethod("getAllLoadedLevelWrappers").invoke(worldProxy);
                    for (Object wrapper : wrappers) {
                        Object level = wrapper.getClass().getMethod("getWrappedMcObject").invoke(wrapper);
                        if (!(level instanceof ServerLevel serverLevel) || !registered.add(level)) continue;
                        Generator handler = new Generator(server, serverLevel, wrapper, DistantHorizonsHandover.forLevel(serverLevel, wrapper));
                        generators.add(handler);
                        Object generator = Proxy.newProxyInstance(generatorType.getClassLoader(), new Class<?>[]{generatorType}, handler);
                        boolean late = bound.invoke(injector, wrapper) != null;
                        Object result = registerOverride.invoke(register, wrapper, generator);
                        boolean success = result.getClass().getField("success").getBoolean(result);
                        if (!success) {
                            LOG.warn("Distant Horizons refused this mod's generator for {} ({}); it keeps using its own",
                                    serverLevel.dimension().location(), result.getClass().getField("message").get(result));
                        } else if (late) {
                            LOG.warn("Distant Horizons had already chosen its own generator for {}; this mod's takes over only if"
                                    + " Distant Horizons restarts its generation for that dimension", serverLevel.dimension().location());
                        } else {
                            LOG.info(HYBRID
                                    ? "Distant Horizons' chunk generation for {} goes through the server's chunk system; its rough"
                                    + " surface generator is unchanged (distant_horizons.generator = \"off\" leaves it alone)"
                                    : "Distant Horizons gets all its distant terrain for {} as finished chunks from the server's chunk"
                                    + " system; its rough surface generator is not used (distant_horizons.generator = \"direct\")",
                                    serverLevel.dimension().location());
                        }
                    }
                }
                if (System.nanoTime() - swept > 2_000_000_000L) {
                    swept = System.nanoTime();
                    for (Generator generator : generators) generator.letGo(AHEAD_EXPIRY_NANOS);
                    if (PERIODIC_LOG && ++sweeps % 5 == 0) {
                        LOG.info("{}; requests {} started, {} answered", status(), REQUESTS.get(), REQUESTS_DONE.get());
                    }
                }
                Thread.sleep(System.nanoTime() - started < 120_000_000_000L ? 10 : 2000);
            }
        } catch (InterruptedException stopped) {
            // server stopping
        } catch (ReflectiveOperationException | RuntimeException | LinkageError failure) {
            LOG.warn("Could not connect to Distant Horizons' generator API ({}); it keeps using its own generator", failure.toString());
        }
    }

    /** IDhApiWorldGenerator, implemented through a proxy so that Distant Horizons is not needed to build or load this mod. */
    private static final class Generator implements InvocationHandler {
        private final MinecraftServer server;
        private final ServerLevel level;
        /** Null when Distant Horizons' own handling of these chunks cannot be switched off. */
        private final DistantHorizonsHandover handover;
        /** Chunks started ahead of Distant Horizons and not yet asked for by it; guarded by this. */
        private final Long2ObjectOpenHashMap<Ahead> ahead = new Long2ObjectOpenHashMap<>();
        /** Chunks already handed over, so that they are not started ahead again; guarded by this. */
        private final LongOpenHashSet served = new LongOpenHashSet();

        private record Ahead(CompletableFuture<ChunkAccess> chunk, long requestedNanos) {}

        private final Object levelWrapper;
        /** Distant Horizons' own generator for this level, made on first use (hybrid mode). */
        private Object inner;

        Generator(MinecraftServer server, ServerLevel level, Object levelWrapper, DistantHorizonsHandover handover) {
            this.server = server;
            this.level = level;
            this.levelWrapper = levelWrapper;
            this.handover = handover;
        }

        private synchronized Object inner() throws ReflectiveOperationException {
            if (inner == null) {
                Object dhLevel = levelWrapper.getClass().getMethod("getDhLevel").invoke(levelWrapper);
                if (dhLevel == null) throw new IllegalStateException("Distant Horizons has no level for " + level.dimension().location() + " yet");
                Class<?> levelType = Class.forName("com.seibel.distanthorizons.core.level.IDhServerLevel");
                inner = Class.forName("com.seibel.distanthorizons.core.generation.DhWorldGenerator").getConstructor(levelType).newInstance(dhLevel);
            }
            return inner;
        }

        /** Whether Distant Horizons' current plan includes generating chunks at all (as opposed to rough surface only). */
        private static boolean planGeneratesChunks() {
            try {
                Object configs = Class.forName("com.seibel.distanthorizons.api.DhApi$Delayed").getField("configs").get(null);
                Object worldGenerator = configs.getClass().getMethod("worldGenerator").invoke(configs);
                Object plan = worldGenerator.getClass().getMethod("GeneratorPlan").invoke(worldGenerator);
                Object value = plan.getClass().getMethod("getValue").invoke(plan);
                return value.getClass().getField("chunkGenEnabled").getBoolean(value);
            } catch (ReflectiveOperationException | RuntimeException unknown) {
                return false;
            }
        }

        /**
         * Hybrid mode.  Everything is Distant Horizons' own generator, except that a request it would answer
         * by generating chunks itself is answered through the server instead (its INTERNAL_SERVER mode), with
         * those chunks and their neighbours already started here so that they are ready when it asks.
         */
        private Object hybrid(Object proxy, Method method, Object[] arguments) throws Throwable {
            switch (method.getName()) {
                case "getPriority":
                    return InvocationHandler.invokeDefault(proxy, method, arguments);
                case "equals":
                    return proxy == arguments[0];
                case "hashCode":
                    return System.identityHashCode(proxy);
                case "toString":
                    return "WorldgenNext generator around Distant Horizons' own for " + level.dimension().location();
                default:
            }
            Object inner = inner();
            Runnable after = null;
            if (method.getName().equals("close")) {
                letGo(0);
            } else if (method.getName().equals("generateLod") && (byte) arguments[4] == 0
                    && ((Enum<?>) arguments[6]).name().equals("FEATURES") && planGeneratesChunks()) {
                @SuppressWarnings({"unchecked", "rawtypes"})
                Object throughServer = Enum.valueOf((Class) ((Enum<?>) arguments[6]).getDeclaringClass(), "INTERNAL_SERVER");
                arguments[6] = throughServer;
                after = startTile((int) arguments[0], (int) arguments[1], 4);
            }
            Object result;
            try {
                result = method.invoke(inner, arguments);
            } catch (java.lang.reflect.InvocationTargetException thrown) {
                if (after != null) after.run();
                throw thrown.getCause();
            }
            if (after != null) {
                Runnable release = after;
                ((CompletableFuture<?>) result).whenComplete((nothing, failure) -> release.run());
            }
            return result;
        }

        /** Starts a tile's chunks and its neighbours; the returned action lets the tile's chunks go again. */
        private Runnable startTile(int minX, int minZ, int width) {
            REQUESTS.incrementAndGet();
            ChunkPos[] positions = new ChunkPos[width * width];
            synchronized (this) {
                if (served.size() > 8_000_000) served.clear();
                for (int i = 0; i < positions.length; i++) {
                    ChunkPos pos = new ChunkPos(minX + i % width, minZ + i / width);
                    positions[i] = pos;
                    if (handover != null) handover.handingOver(pos);
                    served.add(pos.toLong());
                    if (ahead.remove(pos.toLong()) != null) AHEAD_USED.incrementAndGet();
                    else request(pos);
                }
                startAhead(minX, minZ, width, System.nanoTime());
            }
            letGo(AHEAD_EXPIRY_NANOS);
            return () -> {
                REQUESTS_DONE.incrementAndGet();
                CHUNKS.addAndGet(positions.length);
                server.execute(() -> {
                    for (ChunkPos pos : positions) release(pos);
                });
            };
        }

        @Override
        public Object invoke(Object proxy, Method method, Object[] arguments) throws Throwable {
            if (HYBRID) return hybrid(proxy, method, arguments);
            switch (method.getName()) {
                case "getSmallestDataDetailLevel":
                    return (byte) 0;
                case "getLargestDataDetailLevel":
                    // Always 4x4-chunk tiles.  With larger ones Distant Horizons stopped asking after a few seconds
                    // in a singleplayer world (3.3.3).
                    return (byte) 0;
                case "generateChunks":
                    @SuppressWarnings("unchecked")
                    Consumer<Object[]> consumer = (Consumer<Object[]>) arguments[6];
                    return generateChunks((int) arguments[0], (int) arguments[1], (int) arguments[2], (ExecutorService) arguments[5], consumer);
                case "preGeneratorTaskStart":
                    return null;
                case "close":
                    letGo(0);
                    return null;
                case "equals":
                    return proxy == arguments[0];
                case "hashCode":
                    return System.identityHashCode(proxy);
                case "toString":
                    return "WorldgenNext chunk-system generator for " + level.dimension().location();
                default:
                    if (method.isDefault()) return InvocationHandler.invokeDefault(proxy, method, arguments);
                    throw new UnsupportedOperationException(method.toString());
            }
        }

        /**
         * Hands every chunk of the tile to Distant Horizons as the chunk system finishes it, and starts the
         * tiles around this one as well: Distant Horizons works outwards and keeps only one small tile per
         * worker thread in progress, fewer chunks than the chunk system can generate at once, so chunks it is
         * about to ask for are started now and kept loaded until it does.
         *
         * <p>Its consumer appends to a plain list, so calls are serialised; it builds the level-of-detail data
         * on whichever thread completes the returned future, so that completion is moved to the executor it
         * supplied rather than left on the server thread.</p>
         */
        private CompletableFuture<Void> generateChunks(int minX, int minZ, int width, ExecutorService executor, Consumer<Object[]> consumer) {
            int count = width * width;
            REQUESTS.incrementAndGet();
            ChunkPos[] positions = new ChunkPos[count];
            @SuppressWarnings("unchecked")
            CompletableFuture<ChunkAccess>[] chunks = new CompletableFuture[count];
            synchronized (this) {
                if (served.size() > 8_000_000) served.clear();
                for (int i = 0; i < count; i++) {
                    ChunkPos pos = new ChunkPos(minX + i % width, minZ + i / width);
                    positions[i] = pos;
                    if (handover != null) handover.handingOver(pos);
                    Ahead early = ahead.remove(pos.toLong());
                    served.add(pos.toLong());
                    if (early != null) AHEAD_USED.incrementAndGet();
                    chunks[i] = early != null ? early.chunk : request(pos);
                }
                startAhead(minX, minZ, width, System.nanoTime());
            }
            letGo(AHEAD_EXPIRY_NANOS);
            Object lock = new Object();
            CompletableFuture<?>[] pending = new CompletableFuture<?>[count];
            for (int i = 0; i < count; i++) {
                pending[i] = chunks[i].thenAccept(generated -> {
                    synchronized (lock) {
                        consumer.accept(new Object[]{generated, level});
                    }
                    CHUNKS.incrementAndGet();
                });
            }
            CompletableFuture<Void> done = new CompletableFuture<>();
            CompletableFuture.allOf(pending).whenComplete((nothing, failure) -> {
                REQUESTS_DONE.incrementAndGet();
                if (failure != null && handover != null) {
                    for (ChunkPos pos : positions) handover.notHandedOver(pos);
                }
                server.execute(() -> {
                    for (ChunkPos pos : positions) release(pos);
                });
                try {
                    executor.execute(() -> complete(done, failure));
                } catch (RuntimeException rejected) {
                    // Distant Horizons is shutting its pool down; finish where we are.
                    complete(done, failure);
                }
            });
            return done;
        }

        /** Starts the tiles around the given one, nearest ring first, until the window is full.  Holds this. */
        private void startAhead(int minX, int minZ, int width, long now) {
            int rings = AHEAD_REACH / width;
            for (int ring = 1; ring <= rings; ring++) {
                for (int[] offset : TileRings.offsets(ring)) {
                    if (ahead.size() >= AHEAD_WINDOW) return;
                    int tileX = minX + offset[0] * width;
                    int tileZ = minZ + offset[1] * width;
                    for (int i = 0; i < width * width; i++) {
                        ChunkPos pos = new ChunkPos(tileX + i % width, tileZ + i / width);
                        long key = pos.toLong();
                        if (served.contains(key) || ahead.containsKey(key)) continue;
                        // Its load event comes long before Distant Horizons asks for it, so that is switched off now.
                        if (handover != null) handover.handingOver(pos);
                        ahead.put(key, new Ahead(request(pos), now));
                    }
                }
            }
        }

        private CompletableFuture<ChunkAccess> request(ChunkPos pos) {
            ServerChunkCache cache = level.getChunkSource();
            server.execute(() -> cache.addRegionTicket(TICKET, pos, 0, pos));
            return cache.getChunkFuture(pos.x, pos.z, ChunkStatus.FULL, true).thenApply(result -> {
                ChunkAccess chunk = result.orElse(null);
                if (chunk == null) {
                    throw new IllegalStateException("chunk " + pos + " was not generated: " + result.getError());
                }
                return chunk;
            });
        }

        /** Server thread. */
        private void release(ChunkPos pos) {
            level.getChunkSource().removeRegionTicket(TICKET, pos, 0, pos);
        }

        /**
         * Lets go of chunks that were started ahead longer ago than the given time and never asked for.  Called
         * with every request and, because requests can simply stop, by the bridge's thread every few seconds.
         * Distant Horizons is told to treat such a chunk normally again, so it builds it when it is saved.
         */
        void letGo(long olderThanNanos) {
            LongArrayList stale = new LongArrayList();
            synchronized (this) {
                long now = System.nanoTime();
                var entries = ahead.long2ObjectEntrySet().iterator();
                while (entries.hasNext()) {
                    var entry = entries.next();
                    if (now - entry.getValue().requestedNanos >= olderThanNanos) {
                        stale.add(entry.getLongKey());
                        entries.remove();
                    }
                }
            }
            if (stale.isEmpty()) return;
            AHEAD_EXPIRED.addAndGet(stale.size());
            server.execute(() -> stale.forEach(key -> {
                ChunkPos pos = new ChunkPos(key);
                if (handover != null) handover.notHandedOver(pos);
                release(pos);
            }));
        }

        private static void complete(CompletableFuture<Void> done, Throwable failure) {
            if (failure == null) done.complete(null);
            else done.completeExceptionally(failure);
        }
    }

    /** One line for the status report, or null when Distant Horizons is not installed. */
    public static String status() {
        if (!installed()) return null;
        if (!ENABLED) return "Distant Horizons: installed and left alone (distant_horizons.generator = \"off\")";
        return String.format(Locale.ROOT, "Distant Horizons (" + MODE + "): %,d chunks provided from the chunk system so far (%,d of them started before"
                + " it asked, %,d started and never asked for)%s",
                CHUNKS.get(), AHEAD_USED.get(), AHEAD_EXPIRED.get(), DistantHorizonsHandover.SKIPPED.get() > 0
                        ? String.format(Locale.ROOT, "; its second build of the same chunk skipped for %,d, %,d of those still loaded and unsaved",
                                DistantHorizonsHandover.SKIPPED.get(), DistantHorizonsHandover.waitingForFirstSave())
                        : "");
    }
}
