// SPDX-License-Identifier: MIT
package dev.worldgennext.neoforge.compat;

import dev.worldgennext.neoforge.version.Version;

import dev.worldgennext.neoforge.loader.Loader;

import it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap;
import it.unimi.dsi.fastutil.longs.LongArrayList;
import it.unimi.dsi.fastutil.longs.LongOpenHashSet;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ChunkLevel;
import net.minecraft.server.level.FullChunkStatus;
import net.minecraft.server.level.ServerChunkCache;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.ChunkPos;
import net.minecraft.world.level.chunk.ChunkAccess;
import net.minecraft.world.level.chunk.status.ChunkStatus;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.lang.reflect.InvocationHandler;
import java.lang.reflect.Method;
import java.lang.reflect.Proxy;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.IdentityHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.atomic.AtomicLong;
import java.util.function.Consumer;

/**
 * Sends Distant Horizons' chunk generation through the server's chunk system.
 *
 * <p>Distant Horizons builds distant terrain two ways: a rough surface generator that samples heights, and a
 * chunk generator of its own that runs outside the chunk system, one small tile (4x4 chunks) per worker
 * thread.  With this mod the chunk system is the faster source of chunks, so this class registers a world
 * generator override through Distant Horizons' API.  In "hybrid" mode the override wraps Distant Horizons'
 * own generator and only takes over its chunk requests, converting the chunks with Distant Horizons' converter
 * on this mod's threads ({@link DistantHorizonsConverter}); in "direct" mode it answers every request with
 * finished chunks itself.  In both, the tiles around a request are started early so that enough chunks are
 * in flight, and {@link DistantHorizonsHandover} keeps Distant Horizons from building them twice.</p>
 *
 * <p>The chunks are real: they are saved in the world like chunks generated by Distant Horizons'
 * INTERNAL_SERVER mode.  Distant Horizons is not a build dependency; everything goes through reflection and
 * a dynamic proxy, and nothing here runs unless the mod is installed.  Measurements and limits:
 * docs/evidence/comparison-distant-horizons.md.</p>
 */
public final class DistantHorizonsBridge {
    /**
     * "hybrid" (the default): Distant Horizons' own generator stays in charge, with its rough surface for far
     * terrain and its plan, and only its chunk generation is sent through the server's chunk system.
     * "direct": every request is answered with finished chunks, through its public API only; its rough surface
     * generator is then not used at all, so far terrain appears only as chunks are finished.
     * "off": Distant Horizons is left alone.
     */
    private static final String MODE = mode(System.getProperty("worldgennext.dh.mode", "hybrid"));
    public static final boolean ENABLED = !MODE.equals("off");
    private static final boolean HYBRID = MODE.equals("hybrid");
    /**
     * Most chunks started ahead of Distant Horizons' requests at one time; 0 turns that off.  Unless set, one
     * chunk per 4 MB of heap, at most 4,096: these are finished chunks waiting to be asked for.
     */
    private static final int AHEAD_WINDOW = Math.max(0, Integer.getInteger("worldgennext.dh.readAhead",
            (int) Math.min(4096, Runtime.getRuntime().maxMemory() / (4L << 20))));
    /** How far from a requested tile tiles are started ahead, in chunks. */
    private static final int AHEAD_REACH = Math.max(0, Integer.getInteger("worldgennext.dh.readAheadReach", 32));
    /** A chunk started ahead and not asked for within this time is let go. */
    private static final long AHEAD_EXPIRY_NANOS = 30_000_000_000L;
    private static final Logger LOG = LoggerFactory.getLogger("worldgennext");
    private static final Version.Ticket TICKET = Version.ticket("worldgennext_dh");

    private static volatile Thread watcher;
    private static final AtomicLong CHUNKS = new AtomicLong();
    private static final AtomicLong AHEAD_USED = new AtomicLong();
    private static final AtomicLong REQUESTS = new AtomicLong();
    private static final AtomicLong REQUESTS_DONE = new AtomicLong();
    private static final AtomicLong ANSWER_NANOS = new AtomicLong();
    /** -Dworldgennext.dh.log=true writes the counters to the log every ten seconds. */
    private static final boolean PERIODIC_LOG = Boolean.getBoolean("worldgennext.dh.log");
    private static final AtomicLong AHEAD_EXPIRED = new AtomicLong();

    private DistantHorizonsBridge() {}

    private static String mode(String value) {
        String mode = value.trim().toLowerCase(Locale.ROOT);
        return mode.equals("direct") || mode.equals("off") ? mode : "hybrid";
    }

    public static boolean installed() {
        return Loader.isModLoaded("distanthorizons");
    }

    /** Chunks handed to Distant Horizons since the server started. */
    public static long chunksProvided() {
        return CHUNKS.get();
    }

    /**
     * Registers the override for every server level Distant Horizons loads.  Distant Horizons chooses a level's
     * generator once, about half a second after it loads the level, so this starts before the levels exist and
     * looks often.
     */
    public static void serverStarting(MinecraftServer server) {
        if (!ENABLED || !installed()) return;
        CHUNKS.set(0);
        AHEAD_USED.set(0);
        REQUESTS.set(0);
        REQUESTS_DONE.set(0);
        ANSWER_NANOS.set(0);
        AHEAD_EXPIRED.set(0);
        DistantHorizonsHandover.SKIPPED.set(0);
        DistantHorizonsColumns.COLUMNS_CHECKED.set(0);
        DistantHorizonsColumns.TILES_CHANGED.set(0);
        DistantHorizonsConverter.TILES_WRITTEN.set(0);
        DistantHorizonsConverter.TILES_BUILT.set(0);
        DistantHorizonsColumns.POINTS_CHECKED.set(0);
        DistantHorizonsColumns.COLUMNS_DIFFERENT.set(0);
        Thread thread = new Thread(() -> watch(server), "worldgennext-dh-bridge");
        thread.setDaemon(true);
        watcher = thread;
        thread.start();
    }

    public static void serverStopping() {
        Thread thread = watcher;
        watcher = null;
        if (thread != null) thread.interrupt();
        DistantHorizonsHandover.serverStopping();
    }

    private static void watch(MinecraftServer server) {
        Set<Object> registered = Collections.newSetFromMap(new IdentityHashMap<>());
        List<Generator> generators = new ArrayList<>();
        long swept = System.nanoTime();
        int sweeps = 0;
        try {
            Class<?> delayed = Class.forName("com.seibel.distanthorizons.api.DhApi$Delayed");
            Class<?> api = Class.forName("com.seibel.distanthorizons.api.DhApi");
            Class<?> generatorType = Class.forName("com.seibel.distanthorizons.api.interfaces.override.worldGenerator.IDhApiWorldGenerator");
            Class<?> wrapperType = Class.forName("com.seibel.distanthorizons.api.interfaces.world.IDhApiLevelWrapper");
            Object register = api.getField("worldGenOverrides").get(null);
            Method registerOverride = register.getClass().getMethod("registerWorldGeneratorOverride", wrapperType, generatorType);
            Object injector = Class.forName("com.seibel.distanthorizons.coreapi.DependencyInjection.WorldGeneratorInjector")
                    .getField("INSTANCE").get(null);
            Method bound = injector.getClass().getMethod("get", wrapperType);
            if (HYBRID) {
                // Distant Horizons' own generator is not part of its API.  Without it there is nothing to wrap.
                try {
                    Class.forName("com.seibel.distanthorizons.core.generation.DhWorldGenerator")
                            .getConstructor(Class.forName("com.seibel.distanthorizons.core.level.IDhServerLevel"));
                    Class.forName("com.seibel.distanthorizons.core.wrapperInterfaces.world.ILevelWrapper").getMethod("getDhLevel");
                } catch (ReflectiveOperationException | LinkageError missing) {
                    LOG.warn("This version of Distant Horizons does not have the generator class this mod wraps ({}); it keeps"
                            + " using its own generator.  distant_horizons.generator = \"direct\" does not need that class.",
                            missing.toString());
                    return;
                }
            }
            DistantHorizonsHandover.prepare();
            if (HYBRID) DistantHorizonsConverter.prepare();
            long started = System.nanoTime();
            while (watcher == Thread.currentThread()) {
                Object worldProxy = delayed.getField("worldProxy").get(null);
                if (worldProxy != null && (boolean) worldProxy.getClass().getMethod("worldLoaded").invoke(worldProxy)) {
                    Iterable<?> wrappers = (Iterable<?>) worldProxy.getClass().getMethod("getAllLoadedLevelWrappers").invoke(worldProxy);
                    for (Object wrapper : wrappers) {
                        Object level = wrapper.getClass().getMethod("getWrappedMcObject").invoke(wrapper);
                        if (!(level instanceof ServerLevel serverLevel) || !registered.add(level)) continue;
                        Generator handler = new Generator(server, serverLevel, wrapper, DistantHorizonsHandover.forLevel(serverLevel, wrapper));
                        generators.add(handler);
                        Object generator = Proxy.newProxyInstance(generatorType.getClassLoader(), new Class<?>[]{generatorType}, handler);
                        boolean late = bound.invoke(injector, wrapper) != null;
                        Object result = registerOverride.invoke(register, wrapper, generator);
                        boolean success = result.getClass().getField("success").getBoolean(result);
                        if (!success) {
                            LOG.warn("Distant Horizons refused this mod's generator for {} ({}); it keeps using its own",
                                    serverLevel.dimension().location(), result.getClass().getField("message").get(result));
                        } else if (late) {
                            LOG.warn("Distant Horizons had already chosen its own generator for {}; this mod's takes over only if"
                                    + " Distant Horizons restarts its generation for that dimension", serverLevel.dimension().location());
                        } else {
                            LOG.info(HYBRID
                                    ? "Distant Horizons' chunk generation for {} goes through the server's chunk system; its rough"
                                    + " surface generator is unchanged (distant_horizons.generator = \"off\" leaves it alone)"
                                    : "Distant Horizons gets all its distant terrain for {} as finished chunks from the server's chunk"
                                    + " system; its rough surface generator is not used (distant_horizons.generator = \"direct\")",
                                    serverLevel.dimension().location());
                        }
                    }
                }
                if (System.nanoTime() - swept > 2_000_000_000L) {
                    swept = System.nanoTime();
                    for (Generator generator : generators) generator.letGo(AHEAD_EXPIRY_NANOS);
                    if (PERIODIC_LOG && ++sweeps % 5 == 0) {
                        LOG.info("{}; requests {} started, {} answered, {} ms each on average", status(), REQUESTS.get(),
                                REQUESTS_DONE.get(), ANSWER_NANOS.get() / 1_000_000 / Math.max(1, REQUESTS_DONE.get()));
                    }
                }
                Thread.sleep(System.nanoTime() - started < 120_000_000_000L ? 10 : 2000);
            }
        } catch (InterruptedException stopped) {
            // server stopping
        } catch (ReflectiveOperationException | RuntimeException | LinkageError failure) {
            LOG.warn("Could not connect to Distant Horizons' generator API ({}); it keeps using its own generator", failure.toString());
        }
    }

    /** IDhApiWorldGenerator, implemented through a proxy so that Distant Horizons is not needed to build or load this mod. */
    private static final class Generator implements InvocationHandler {
        /** Distant Horizons asks for chunk detail in tiles of this many chunks a side; its tiles are aligned to it. */
        private static final int TILE = 4;
        /**
         * Hybrid mode, unless distant_horizons.full_chunks is set: chunks for Distant Horizons stop at FEATURES
         * instead of going on to FULL, and a tile is converted once the chunks around it have reached FEATURES
         * too.  What is left out is vanilla light, mob spawning and the promotion to a full chunk, none of which
         * Distant Horizons uses.  The chunk is saved unfinished, as the game saves any partly generated chunk,
         * and is finished when a player gets there.
         */
        private static final boolean LOD_ONLY = HYBRID && !Boolean.getBoolean("worldgennext.dh.fullChunks");
        private static final ChunkStatus STATUS = LOD_ONLY ? ChunkStatus.FEATURES : ChunkStatus.FULL;
        /** A region ticket's level is that of a full chunk less its radius; a negative radius gives the level this status needs. */
        private static final int TICKET_RADIUS = ChunkLevel.byStatus(FullChunkStatus.FULL) - ChunkLevel.byStatus(STATUS);

        private final MinecraftServer server;
        private final ServerLevel level;
        private final Object levelWrapper;
        /** Null when Distant Horizons' own handling of these chunks cannot be switched off. */
        private final DistantHorizonsHandover handover;
        /** Tiles started ahead of Distant Horizons and not yet asked for by it, by their corner chunk; guarded by this. */
        private final Long2ObjectOpenHashMap<Tile> ahead = new Long2ObjectOpenHashMap<>();
        /** Tiles already handed over, so that they are not started ahead again; guarded by this. */
        private final LongOpenHashSet served = new LongOpenHashSet();
        /** Distant Horizons' own generator for this level and its level object, made on first use (hybrid mode). */
        private Object inner;
        private Object dhLevel;
        /**
         * Chunks that may be started ahead right now: grows while Distant Horizons asks for what was started
         * and shrinks when tiles were started for nothing (it already had them, or went elsewhere).  Guarded by this.
         */
        private int budget = AHEAD_WINDOW;

        /** One 4x4-chunk tile: its chunks as the chunk system finishes them. */
        private record Tile(ChunkPos[] positions, CompletableFuture<ChunkAccess>[] chunks, ChunkPos[] held,
                            CompletableFuture<Void> settled, long requestedNanos) {}

        Generator(MinecraftServer server, ServerLevel level, Object levelWrapper, DistantHorizonsHandover handover) {
            this.server = server;
            this.level = level;
            this.levelWrapper = levelWrapper;
            this.handover = handover;
        }

        private synchronized Object inner() throws ReflectiveOperationException {
            if (inner == null) {
                dhLevel = levelWrapper.getClass().getMethod("getDhLevel").invoke(levelWrapper);
                if (dhLevel == null) throw new IllegalStateException("Distant Horizons has no level for " + level.dimension().location() + " yet");
                Class<?> levelType = Class.forName("com.seibel.distanthorizons.core.level.IDhServerLevel");
                inner = Class.forName("com.seibel.distanthorizons.core.generation.DhWorldGenerator").getConstructor(levelType).newInstance(dhLevel);
            }
            return inner;
        }

        /** Whether Distant Horizons' current plan includes generating chunks at all (as opposed to rough surface only). */
        private static boolean planGeneratesChunks() {
            try {
                Object configs = Class.forName("com.seibel.distanthorizons.api.DhApi$Delayed").getField("configs").get(null);
                Object worldGenerator = configs.getClass().getMethod("worldGenerator").invoke(configs);
                Object plan = worldGenerator.getClass().getMethod("GeneratorPlan").invoke(worldGenerator);
                Object value = plan.getClass().getMethod("getValue").invoke(plan);
                return value.getClass().getField("chunkGenEnabled").getBoolean(value);
            } catch (ReflectiveOperationException | RuntimeException unknown) {
                return false;
            }
        }

        @Override
        public Object invoke(Object proxy, Method method, Object[] arguments) throws Throwable {
            switch (method.getName()) {
                case "equals":
                    return proxy == arguments[0];
                case "hashCode":
                    return System.identityHashCode(proxy);
                case "toString":
                    return "WorldgenNext generator (" + MODE + ") for " + level.dimension().location();
                case "getPriority":
                    return InvocationHandler.invokeDefault(proxy, method, arguments);
                default:
            }
            return HYBRID ? hybrid(method, arguments) : direct(proxy, method, arguments);
        }

        /**
         * Hybrid mode.  Everything is Distant Horizons' own generator, except a request for a full-detail tile
         * that it would answer by generating chunks itself.  Those chunks come from the chunk system instead
         * and are converted here with Distant Horizons' converter; where that converter cannot be reached the
         * request is passed on in its INTERNAL_SERVER mode, which asks the server for the chunks itself.
         */
        private Object hybrid(Method method, Object[] arguments) throws Throwable {
            Object inner = inner();
            Runnable after = null;
            if (method.getName().equals("close")) {
                letGo(0);
            } else if (method.getName().equals("generateLod") && (byte) arguments[4] == 0 && planGeneratesChunks()) {
                String mode = ((Enum<?>) arguments[6]).name();
                if (DistantHorizonsConverter.available() && (mode.equals("FEATURES") || mode.equals("INTERNAL_SERVER"))) {
                    @SuppressWarnings("unchecked")
                    Consumer<Object> consumer = (Consumer<Object>) arguments[8];
                    return convertTile((int) arguments[0], (int) arguments[1], arguments[5], consumer);
                }
                if (mode.equals("FEATURES")) {
                    @SuppressWarnings({"unchecked", "rawtypes"})
                    Object throughServer = Enum.valueOf((Class) ((Enum<?>) arguments[6]).getDeclaringClass(), "INTERNAL_SERVER");
                    arguments[6] = throughServer;
                    Tile tile = take((int) arguments[0], (int) arguments[1]);
                    REQUESTS.incrementAndGet();
                    after = () -> {
                        REQUESTS_DONE.incrementAndGet();
                        CHUNKS.addAndGet(tile.positions.length);
                        release(tile, false);
                    };
                }
            }
            Object result;
            try {
                result = method.invoke(inner, arguments);
            } catch (java.lang.reflect.InvocationTargetException thrown) {
                if (after != null) after.run();
                throw thrown.getCause();
            }
            if (after != null) {
                Runnable release = after;
                ((CompletableFuture<?>) result).whenComplete((nothing, failure) -> release.run());
            }
            return result;
        }

        /** Direct mode: Distant Horizons' public API only, every request answered with finished chunks. */
        private Object direct(Object proxy, Method method, Object[] arguments) throws Throwable {
            switch (method.getName()) {
                case "getSmallestDataDetailLevel":
                case "getLargestDataDetailLevel":
                    // Always 4x4-chunk tiles.  With larger ones Distant Horizons stopped asking after a few seconds
                    // in a singleplayer world (3.3.3).
                    return (byte) 0;
                case "generateChunks":
                    @SuppressWarnings("unchecked")
                    Consumer<Object[]> consumer = (Consumer<Object[]>) arguments[6];
                    return generateChunks((int) arguments[0], (int) arguments[1], (int) arguments[2], (ExecutorService) arguments[5], consumer);
                case "preGeneratorTaskStart":
                    return null;
                case "close":
                    letGo(0);
                    return null;
                default:
                    if (method.isDefault()) return InvocationHandler.invokeDefault(proxy, method, arguments);
                    throw new UnsupportedOperationException(method.toString());
            }
        }

        /**
         * Hands every chunk of the tile to Distant Horizons as the chunk system finishes it.  Its consumer
         * appends to a plain list, so calls are serialised; it builds the level-of-detail data on whichever
         * thread completes the returned future, so that completion is moved to the executor it supplied rather
         * than left on the server thread.
         */
        private CompletableFuture<Void> generateChunks(int minX, int minZ, int width, ExecutorService executor, Consumer<Object[]> consumer) {
            if (width != TILE) throw new UnsupportedOperationException("tile of " + width + " chunks");
            REQUESTS.incrementAndGet();
            Tile tile = take(minX, minZ);
            Object lock = new Object();
            CompletableFuture<?>[] pending = new CompletableFuture<?>[tile.chunks.length];
            for (int i = 0; i < pending.length; i++) {
                pending[i] = tile.chunks[i].thenAccept(generated -> {
                    synchronized (lock) {
                        consumer.accept(new Object[]{generated, level});
                    }
                    CHUNKS.incrementAndGet();
                });
            }
            CompletableFuture<Void> done = new CompletableFuture<>();
            CompletableFuture.allOf(pending).whenComplete((nothing, failure) -> {
                REQUESTS_DONE.incrementAndGet();
                release(tile, failure != null);
                try {
                    executor.execute(() -> complete(done, failure));
                } catch (RuntimeException rejected) {
                    // Distant Horizons is shutting its pool down; finish where we are.
                    complete(done, failure);
                }
            });
            return done;
        }

        /**
         * Answers a request for a full-detail tile that Distant Horizons would build from chunks: the chunks
         * come from the chunk system and are converted with Distant Horizons' own converter on this mod's
         * threads, into the data source it supplied.
         */
        private CompletableFuture<Void> convertTile(int minX, int minZ, Object tileDataSource, Consumer<Object> consumer) {
            REQUESTS.incrementAndGet();
            long asked = System.nanoTime();
            Tile tile = take(minX, minZ);
            CompletableFuture<Void> done = new CompletableFuture<>();
            tile.settled.whenCompleteAsync((nothing, failure) -> {
                REQUESTS_DONE.incrementAndGet();
                Throwable problem = failure;
                if (problem == null) {
                    try {
                        ChunkAccess[] generated = new ChunkAccess[tile.chunks.length];
                        for (int i = 0; i < generated.length; i++) generated[i] = tile.chunks[i].join();
                        DistantHorizonsConverter.convert(level, dhLevel, levelWrapper, generated, tileDataSource);
                        consumer.accept(tileDataSource);
                        CHUNKS.addAndGet(generated.length);
                    } catch (Throwable thrown) {
                        problem = thrown;
                    }
                }
                release(tile, problem != null);
                ANSWER_NANOS.addAndGet(System.nanoTime() - asked);
                complete(done, problem);
            }, DistantHorizonsConverter.pool());
            return done;
        }

        /**
         * The tile Distant Horizons is asking for: the one started ahead if there is one, a new one otherwise.
         * Also starts the tiles around it.  Distant Horizons works outwards and keeps only one tile per worker
         * thread in progress, fewer chunks than the chunk system can generate at once, so tiles it is about to
         * ask for are started now and kept until it does.
         */
        private Tile take(int minX, int minZ) {
            Tile tile;
            synchronized (this) {
                if (served.size() > 500_000) served.clear();
                long key = ChunkPos.asLong(minX, minZ);
                tile = ahead.remove(key);
                served.add(key);
                if (tile != null) {
                    AHEAD_USED.addAndGet(tile.positions.length);
                    budget = Math.min(AHEAD_WINDOW, budget + 2 * TILE * TILE);
                } else {
                    tile = start(minX, minZ);
                }
                int limit = budget / (TILE * TILE);
                int rings = AHEAD_REACH / TILE;
                ahead:
                for (int ring = 1; ring <= rings; ring++) {
                    for (int[] offset : TileRings.offsets(ring)) {
                        if (ahead.size() >= limit) break ahead;
                        int x = minX + offset[0] * TILE;
                        int z = minZ + offset[1] * TILE;
                        long neighbour = ChunkPos.asLong(x, z);
                        if (served.contains(neighbour) || ahead.containsKey(neighbour)) continue;
                        ahead.put(neighbour, start(x, z));
                    }
                }
            }
            letGo(AHEAD_EXPIRY_NANOS);
            return tile;
        }

        /**
         * Asks the chunk system for a tile's chunks.  In the unfinished-chunk mode the ring of chunks around the
         * tile is asked for as well: a chunk's blocks are final only when its eight neighbours have placed their
         * features too, which a full chunk guarantees and a chunk stopped at FEATURES does not.
         */
        private Tile start(int minX, int minZ) {
            ChunkPos corner = new ChunkPos(minX, minZ);
            int margin = LOD_ONLY ? 1 : 0;
            int side = TILE + 2 * margin;
            ChunkPos[] positions = new ChunkPos[TILE * TILE];
            ChunkPos[] held = new ChunkPos[side * side];
            @SuppressWarnings("unchecked")
            CompletableFuture<ChunkAccess>[] chunks = new CompletableFuture[positions.length];
            CompletableFuture<?>[] all = new CompletableFuture<?>[held.length];
            ServerChunkCache cache = level.getChunkSource();
            for (int i = 0; i < held.length; i++) {
                int dx = i % side - margin, dz = i / side - margin;
                ChunkPos pos = new ChunkPos(minX + dx, minZ + dz);
                held[i] = pos;
                boolean inside = dx >= 0 && dx < TILE && dz >= 0 && dz < TILE;
                // The chunk's load event comes before Distant Horizons has its data from here, so that is switched off now.
                // An unfinished chunk has no such event.
                if (inside && handover != null && !LOD_ONLY) handover.handingOver(pos);
                // The ticket is this tile's own, so that a neighbouring tile letting go does not release it.
                server.execute(() -> TICKET.add(cache, pos, TICKET_RADIUS, corner));
                CompletableFuture<ChunkAccess> chunk = cache.getChunkFuture(pos.x, pos.z, STATUS, true).thenApply(result -> {
                    ChunkAccess generated = result.orElse(null);
                    if (generated == null) {
                        throw new IllegalStateException("chunk " + pos + " was not generated: " + result.getError());
                    }
                    return generated;
                });
                all[i] = chunk;
                if (inside) {
                    positions[dz * TILE + dx] = pos;
                    chunks[dz * TILE + dx] = chunk;
                }
            }
            return new Tile(positions, chunks, held, CompletableFuture.allOf(all), System.nanoTime());
        }

        /** Lets a tile's chunks unload.  A tile that Distant Horizons did not get is treated by it as any other chunk again. */
        private void release(Tile tile, boolean notHandedOver) {
            if (notHandedOver && handover != null) {
                for (ChunkPos pos : tile.positions) handover.notHandedOver(pos);
            }
            server.execute(() -> {
                ServerChunkCache cache = level.getChunkSource();
                for (ChunkPos pos : tile.held) TICKET.remove(cache, pos, TICKET_RADIUS, tile.positions[0]);
            });
        }

        /**
         * Lets go of tiles that were started ahead longer ago than the given time and never asked for.  Called
         * with every request and, because requests can simply stop, by the bridge's thread every few seconds.
         */
        void letGo(long olderThanNanos) {
            List<Tile> stale = new ArrayList<>();
            synchronized (this) {
                long now = System.nanoTime();
                var tiles = ahead.values().iterator();
                while (tiles.hasNext()) {
                    Tile tile = tiles.next();
                    if (now - tile.requestedNanos >= olderThanNanos) {
                        stale.add(tile);
                        tiles.remove();
                    }
                }
            }
            if (!stale.isEmpty()) {
                synchronized (this) {
                    budget = Math.max(4 * TILE * TILE, budget - stale.size() * TILE * TILE);
                }
            }
            for (Tile tile : stale) {
                AHEAD_EXPIRED.addAndGet(tile.positions.length);
                release(tile, true);
            }
        }

        private static void complete(CompletableFuture<Void> done, Throwable failure) {
            if (failure == null) done.complete(null);
            else done.completeExceptionally(failure);
        }
    }

    /** One line for the status report, or null when Distant Horizons is not installed. */
    public static String status() {
        if (!installed()) return null;
        if (!ENABLED) return "Distant Horizons: installed and left alone (distant_horizons.generator = \"off\")";
        return String.format(Locale.ROOT, "Distant Horizons (" + MODE + "): %,d chunks provided from the chunk system so far (%,d of them started before"
                + " it asked, %,d started and never asked for)%s",
                CHUNKS.get(), AHEAD_USED.get(), AHEAD_EXPIRED.get(), DistantHorizonsHandover.SKIPPED.get() > 0
                        ? String.format(Locale.ROOT, "; its second build of the same chunk skipped for %,d, %,d of those still loaded and unsaved",
                                DistantHorizonsHandover.SKIPPED.get(), DistantHorizonsHandover.waitingForFirstSave())
                        : "")
                + String.format(Locale.ROOT, "; tiles converted here: %,d by this mod's column writer, %,d by Distant Horizons' builder",
                        DistantHorizonsConverter.TILES_WRITTEN.get(), DistantHorizonsConverter.TILES_BUILT.get())
                + (DistantHorizonsColumns.CHECK ? String.format(Locale.ROOT, "; column writer check: %,d columns (%,d data points) compared"
                        + " with Distant Horizons' builder, %,d differ (%,d tiles changed while being checked and were built again)",
                        DistantHorizonsColumns.COLUMNS_CHECKED.get(), DistantHorizonsColumns.POINTS_CHECKED.get(),
                        DistantHorizonsColumns.COLUMNS_DIFFERENT.get(), DistantHorizonsColumns.TILES_CHANGED.get()) : "");
    }
}
