// SPDX-License-Identifier: MIT
package dev.worldgennext.neoforge.compat;

import dev.worldgennext.neoforge.fast.FastNoiseEngine;
import dev.worldgennext.neoforge.loader.Loader;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;

/**
 * How hard the distant-terrain bridges (Distant Horizons, Voxy) may push, so that they do not get in the way of
 * the game itself.
 *
 * <p>Terrain for distant views is worth nothing to a player whose game stutters for it.  Two things made it
 * stutter.  At the start of a session the bridges asked for hundreds of far chunks while the GPU kernels were
 * still being built, so all of them were generated by the slower original code, ahead of the chunks around
 * the player.  And with many hundreds of chunks under way at once, a chunk the game needs now (the one a
 * flying player is about to enter) waits behind them at every step, and the collector has that many more
 * live chunks to copy at every pause.</p>
 *
 * <p>So a bridge starts nothing while a level's kernels are being built ({@link #hold}), and the number of
 * chunks it keeps under way follows the server's ticks ({@link #share}): a tick that comes late takes a
 * part of the allowance away at once, ticks on time give it back gradually.  While a player travels fast
 * (an elytra, a boat on ice) the game needs the chunks ahead of them, a few hundred a second, and the allowance
 * is cut to a part until they slow down: measured in flight at 240 blocks a second, that was the difference
 * between collector pauses of 20 ms and more every second and next to none.</p>
 */
public final class LodPace {
    /** A tick is due every 50 ms; later than this after the one before, it was held up. */
    private static final long LATE_NANOS = 75_000_000L;
    private static final double FLOOR = 0.125, CUT = 0.7, GAIN = 0.01;

    /** Blocks a second: below the first a player is walking or sprinting, from the second on the allowance is at its travelling part. */
    private static final double SLOW = 10.0, FAST = 30.0, TRAVELLING = 0.375;

    private static volatile double share = 1.0;
    private static volatile double travelling = 1.0;
    private static double speed;
    private static final java.util.Map<java.util.UUID, double[]> POSITIONS = new java.util.HashMap<>();
    private static long lastTickEnd;
    private static boolean listening;

    private LodPace() {}

    /** Call once from a bridge when it starts. */
    public static synchronized void listen() {
        if (listening) return;
        listening = true;
        Loader.onServerTickEnd(LodPace::tickEnded);
    }

    private static void tickEnded(MinecraftServer server) {
        long now = System.nanoTime();
        long last = lastTickEnd;
        lastTickEnd = now;
        if (last == 0) return;
        share = now - last > LATE_NANOS ? Math.max(FLOOR, share * CUT) : Math.min(1.0, share + GAIN);
        // The fastest player's horizontal speed, smoothed over about a second.
        double fastest = 0;
        var players = server.getPlayerList().getPlayers();
        for (var player : players) {
            double[] before = POSITIONS.get(player.getUUID());
            if (before != null) fastest = Math.max(fastest, Math.hypot(player.getX() - before[0], player.getZ() - before[1]) * 20.0);
            POSITIONS.put(player.getUUID(), new double[]{player.getX(), player.getZ()});
        }
        if (POSITIONS.size() > players.size()) POSITIONS.keySet().removeIf(id -> server.getPlayerList().getPlayer(id) == null);
        // A teleport is one very fast tick; the smoothing and the cap keep it from counting as travel for long.
        speed += (Math.min(fastest, 4 * FAST) - speed) * 0.1;
        travelling = speed <= SLOW ? 1.0 : speed >= FAST ? TRAVELLING : 1.0 - (1.0 - TRAVELLING) * (speed - SLOW) / (FAST - SLOW);
    }

    /** The part of its usual allowance a bridge may use now, between an eighth and all of it. */
    public static double share() {
        return Math.min(share, travelling);
    }

    /** An allowance scaled by {@link #share}, never below a floor that keeps the bridge moving. */
    public static int allowance(int full, int floor) {
        return Math.max(Math.min(floor, full), (int) (full * share()));
    }

    /** True while the GPU kernels of this level are still being built: far terrain can wait for them. */
    public static boolean hold(ServerLevel level) {
        return FastNoiseEngine.settling(level);
    }
}
