// SPDX-License-Identifier: MIT
package dev.worldgennext.neoforge.fast;

import dev.worldgennext.neoforge.version.Version;

import dev.worldgennext.neoforge.loader.Names;

import net.minecraft.world.level.levelgen.Beardifier;
import net.minecraft.world.level.levelgen.DensityFunction;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * Detects terrain adaptation the kernels do not know about.
 *
 * <p>The GPU reproduces vanilla's Beardifier from its two lists: structure
 * pieces and jigsaw junctions.  Another mod can extend Beardifier by mixin
 * (YUNG's API adds lists of its own and changes compute), and those
 * contributions never reach the GPU.  Fields a mixin adds are ordinary fields
 * of the class at run time, so for each chunk every field that is not one of
 * vanilla's two is inspected: if any holds something (a non-empty list, a
 * pending iterator, an object of unknown meaning) the chunk is generated by
 * the original code.  If another mod changed how Beardifier computes density
 * without adding any field to judge by, every chunk is.  A mod that only
 * changes how vanilla's two lists are filled needs nothing: the kernels read
 * the lists as filled.</p>
 */
final class ForeignBeardifier {
    private static final Logger LOG = LoggerFactory.getLogger("worldgennext-fast");
    private static final Field[] FOREIGN_FIELDS;
    private static final boolean ALWAYS;
    private static final String OWNERS;
    private static final AtomicBoolean REPORTED = new AtomicBoolean();

    static {
        List<Field> fields = new ArrayList<>();
        for (Field field : Beardifier.class.getDeclaredFields()) {
            if (Modifier.isStatic(field.getModifiers())) continue;
            if (Version.BEARD_OWN_FIELDS.stream().anyMatch(own -> field.getName().equals(Names.fieldName(Beardifier.class, own)))) continue;
            try {
                field.setAccessible(true);
                fields.add(field);
            } catch (RuntimeException inaccessible) {
                fields.clear();
                fields.add(null); // marker: cannot judge, treat every chunk as foreign
                break;
            }
        }
        Set<String> owners = new TreeSet<>();
        for (Method method : Beardifier.class.getDeclaredMethods()) {
            for (Annotation annotation : method.getDeclaredAnnotations()) {
                if (!annotation.annotationType().getName().endsWith(".MixinMerged")) continue;
                // A handler that only changes how the two vanilla lists are filled (Lithostitched replaces a piece's
                // terrain adjustment while forStructuresInChunk builds them) is reproduced: the kernels read those
                // lists.  What they cannot reproduce is a change to the density computed from them.
                if (!changesDensity(method)) continue;
                try {
                    String mixin = String.valueOf(annotation.annotationType().getMethod("mixin").invoke(annotation));
                    if (!mixin.startsWith("dev.worldgennext.")) owners.add(mixin);
                } catch (ReflectiveOperationException unreadable) {
                    owners.add("an unidentified mixin");
                }
            }
        }
        boolean unjudgeable = fields.contains(null);
        FOREIGN_FIELDS = unjudgeable ? new Field[0] : fields.toArray(Field[]::new);
        ALWAYS = unjudgeable || !owners.isEmpty() && fields.isEmpty();
        OWNERS = owners.isEmpty() ? "another mod" : String.join(", ", owners);
    }

    /**
     * Whether a method another mod merged into Beardifier takes part in compute.  A handler there receives the
     * sampling position (a FunctionContext, or a ContextProvider for fillArray), or it replaces one of the
     * arithmetic helpers and so deals in numbers only.  Handlers of the list-building code take the lists,
     * pieces or boxes instead.
     */
    private static boolean changesDensity(Method method) {
        Class<?>[] parameters = method.getParameterTypes();
        boolean onlyNumbers = parameters.length > 0;
        for (Class<?> parameter : parameters) {
            if (DensityFunction.FunctionContext.class.isAssignableFrom(parameter)
                    || DensityFunction.ContextProvider.class.isAssignableFrom(parameter)) return true;
            if (!parameter.isPrimitive()) onlyNumbers = false;
        }
        return onlyNumbers || parameters.length == 0 && method.getReturnType() == double.class;
    }

    private ForeignBeardifier() {}

    /** True when this Beardifier carries state, or behaviour, that the kernels would not reproduce. */
    static boolean affects(Beardifier beardifier) throws IllegalAccessException {
        boolean foreign = ALWAYS;
        for (int i = 0; !foreign && i < FOREIGN_FIELDS.length; i++) {
            foreign = holdsSomething(FOREIGN_FIELDS[i].get(beardifier));
        }
        if (foreign && REPORTED.compareAndSet(false, true)) {
            LOG.info("Structure terrain adaptation is extended by {}; {} generated by vanilla code so the result stays the same.", OWNERS,
                    ALWAYS ? "terrain is" : "chunks its structures shape are");
        }
        return foreign;
    }

    private static boolean holdsSomething(Object value) {
        if (value == null) return false;
        if (value instanceof Collection<?> collection) return !collection.isEmpty();
        if (value instanceof Map<?, ?> map) return !map.isEmpty();
        if (value instanceof Iterator<?> iterator) return iterator.hasNext();
        if (value instanceof Object[] array) return array.length > 0;
        if (value instanceof Boolean flag) return flag;
        if (value instanceof Number number) return number.doubleValue() != 0.0;
        return true;
    }
}
