// SPDX-License-Identifier: MIT
package dev.tellurium.neoforge.threading;

import net.minecraft.nbt.CompoundTag;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.locks.LockSupport;
import java.util.function.Supplier;

/**
 * Chunk saving at generation rates on Minecraft 1.21.2 and later.
 *
 * <p>The game copies a chunk on the server thread, turns the copy into NBT on its background pool and hands
 * the IO worker a request that waits for that NBT.  The background pool is the pool that generates chunks, so
 * while chunks are generated by the thousand per second the NBT waits behind generation steps, the IO worker
 * waits for the NBT, and nothing limits how many saves are under way: every chunk generated stays in memory
 * as a copy or as NBT until the heap is full.  Here the NBT is built on threads of this mod's own, which
 * also compress it for the region file (see {@link PrecompressedChunks}), and the server thread starts no
 * further save while more than a bounded number are under way, which holds generation to what the disk
 * takes.</p>
 *
 * <p>What is written is what the game would write, apart from the compression level.</p>
 */
public final class SavePipeline {
    public static final boolean ENABLED = Boolean.parseBoolean(System.getProperty("tellurium.asyncChunkSave", "true"));
    /** Saves under way before the server thread waits: about a twentieth of the heap at some 100 KiB a chunk. */
    public static final int LIMIT = Integer.getInteger("tellurium.asyncChunkSaveLimit",
            (int) Math.max(512, Math.min(8192, Runtime.getRuntime().maxMemory() / (2L << 20))));
    private static final long MAX_WAIT_NANOS = TimeUnit.SECONDS.toNanos(Integer.getInteger("tellurium.asyncChunkSaveWaitSeconds", 10));
    private static final Logger LOG = LoggerFactory.getLogger("tellurium");
    private static final AtomicBoolean WARNED = new AtomicBoolean();
    private static final AtomicInteger IDS = new AtomicInteger();
    private static final ExecutorService POOL = Executors.newFixedThreadPool(
            Math.max(2, Math.min(8, Runtime.getRuntime().availableProcessors() / 3)), task -> {
                Thread thread = new Thread(task, "tellurium-save-" + IDS.incrementAndGet());
                thread.setDaemon(true);
                return thread;
            });

    private SavePipeline() {}

    /** The chunk's NBT, built and compressed on this mod's save threads. */
    public static CompletableFuture<CompoundTag> encode(Supplier<CompoundTag> write) {
        return CompletableFuture.supplyAsync(() -> {
            CompoundTag tag = write.get();
            PrecompressedChunks.prepare(tag);
            return tag;
        }, POOL);
    }

    /**
     * Called on the server thread before a save starts: waits while too many are under way.  Saving needs
     * nothing from the server thread, so the wait ends by itself; it is bounded all the same, and says so once
     * if the bound is reached.
     */
    public static void awaitRoom(AtomicInteger underWay) {
        if (underWay.get() <= LIMIT) return;
        long deadline = System.nanoTime() + MAX_WAIT_NANOS;
        while (underWay.get() > LIMIT) {
            if (System.nanoTime() - deadline > 0) {
                if (WARNED.compareAndSet(false, true)) {
                    LOG.warn("Chunk saving is not keeping up: {} saves under way after waiting {} s; continuing (memory use may grow)",
                            underWay.get(), TimeUnit.NANOSECONDS.toSeconds(MAX_WAIT_NANOS));
                }
                return;
            }
            LockSupport.parkNanos(500_000L);
        }
    }
}
