#!/usr/bin/env python3
"""Compatibility trial of other world-generation mods with Tellurium.

For each group below: download the newest NeoForge 1.21.1 release of every mod in it (and its required
dependencies) from Modrinth into build/test-mods/compat/<group>/, then start a fresh dev server with
gpu.mode = "check" and pregenerate a square.  In check mode chunks are generated by vanilla code and the GPU's
result is compared with them, so a run answers three questions: does the server start and generate without
errors, do the GPU kernels build for that mod's world generator, and do they reproduce it.

Usage: python scripts/test-worldgen-mods.py [group ...]      (no arguments: every group)
Results: build/compat/results.md, one log excerpt per group in build/compat/.
"""
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AGENT = "Tellurium-dev/0.2 (local compatibility test)"
LOADER, GAME = "neoforge", "1.21.1"
# On Windows a bare "bash" started from Python can be WSL's, which cannot run gradlew.bat; prefer Git Bash.
GIT_BASH = Path("C:/Program Files/Git/bin/bash.exe")
BASH = str(GIT_BASH) if GIT_BASH.is_file() else "bash"

# name -> (Modrinth slugs, dimension to pregenerate, radius in chunks)
GROUPS = {
    "biomes-o-plenty": (["biomes-o-plenty"], "", 18),
    "oh-the-biomes-weve-gone": (["oh-the-biomes-weve-gone"], "", 18),
    "regions-unexplored": (["regions-unexplored"], "", 18),
    "natures-spirit": (["natures-spirit"], "", 18),
    "geophilic": (["geophilic"], "", 18),
    "wwoo": (["wwoo"], "", 18),
    "yungs-structures": (["yungs-better-strongholds", "yungs-better-mineshafts", "yungs-better-dungeons", "yungs-better-ocean-monuments",
                          "yungs-better-desert-temples", "yungs-better-jungle-temples", "yungs-better-witch-huts", "yungs-bridges",
                          "yungs-extras"], "", 18),
    # Left out: Towns and Towers (its 1.21.1 release requires NeoForge 21.1.230, newer than this project's
    # development environment) and ChoiceTheorem's Overhauled Village (fails to load on NeoForge 21.1.176 with
    # an event-bus registration error of its own).
    "structure-packs": (["dungeons-and-taverns", "when-dungeons-arise", "structory"], "", 18),
    "the-lost-cities": (["the-lost-cities"], "", 14),
    "nether-mods": (["incendium", "amplified-nether", "yungs-better-nether-fortresses"], "minecraft:the_nether", 14),
    "end-mods": (["nullscape", "yungs-better-end-island"], "minecraft:the_end", 14),
    "incendium": (["incendium"], "minecraft:the_nether", 14),
    "amplified-nether": (["amplified-nether"], "minecraft:the_nether", 14),
    "yungs-nether-fortresses": (["yungs-better-nether-fortresses"], "minecraft:the_nether", 14),
    "nullscape": (["nullscape"], "minecraft:the_end", 14),
}


def get(url):
    request = urllib.request.Request(url, headers={"User-Agent": AGENT})
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read()


def newest_version(project):
    query = urllib.parse.urlencode({"loaders": json.dumps([LOADER]), "game_versions": json.dumps([GAME])})
    versions = json.loads(get(f"https://api.modrinth.com/v2/project/{project}/version?{query}"))
    return versions[0] if versions else None


def collect(slugs):
    """Newest release of each project plus required dependencies, by project id."""
    chosen, queue, missing = {}, list(slugs), []
    while queue:
        project = queue.pop(0)
        version = newest_version(project)
        if version is None:
            missing.append(project)
            continue
        if version["project_id"] in chosen:
            continue
        chosen[version["project_id"]] = version
        for dependency in version.get("dependencies", []):
            if dependency.get("dependency_type") == "required" and dependency.get("project_id") and dependency["project_id"] not in chosen:
                queue.append(dependency["project_id"])
    return chosen, missing


def download(version, folder):
    file = next((f for f in version["files"] if f.get("primary")), version["files"][0])
    target = folder / file["filename"]
    if not target.is_file():
        data = get(file["url"])
        if hashlib.sha512(data).hexdigest() != file["hashes"]["sha512"]:
            raise RuntimeError(f"hash mismatch for {file['filename']}")
        target.write_bytes(data)
    return file["filename"], file["size"]


def run(group, slugs, dimension, radius, results):
    folder = ROOT / "build" / "test-mods" / "compat" / group
    folder.mkdir(parents=True, exist_ok=True)
    for jar in (ROOT / "build" / "test-mods" / "vanilla").glob("*.jar"):
        shutil.copy2(jar, folder / jar.name)
    try:
        chosen, missing = collect(slugs)
        files = [download(version, folder) for version in chosen.values()]
    except Exception as failure:  # noqa: BLE001 - reported per group
        results.append((group, "could not download", str(failure)[:160], ""))
        return
    names = ", ".join(sorted(name for name, _ in files))
    if missing:
        names += " (no NeoForge 1.21.1 release: " + ", ".join(missing) + ")"
    extra = "tellurium.pregen.autostartDimension=" + dimension if dimension else ""
    environment = dict(os.environ, CONFIG="build/check.toml")
    (ROOT / "build" / "check.toml").write_text('[gpu]\nmode = "check"\n')
    try:
        output = subprocess.run([BASH, "scripts/run-pregen.sh", str(radius), f"compat/{group}", extra], cwd=ROOT, env=environment,
                                capture_output=True, text=True, timeout=2400).stdout
    except subprocess.TimeoutExpired:
        results.append((group, "timed out after 40 minutes", "", names))
        return
    out_dir = ROOT / "build" / "compat"
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / f"{group}.txt").write_text(output)
    run_dir = re.search(r"^RUNDIR (.+)$", output, re.M)
    log = Path(run_dir.group(1).strip()) / "logs" / "latest.log" if run_dir else None
    text = log.read_text(errors="replace") if log and log.is_file() else ""
    finished = re.search(r"Pregeneration finished: ([\d,]+) chunks in ([^(]+)\(([\d,]+) chunks/s\)(, [\d,]+ failed)?", text)
    check = re.search(r"([\d,]+) chunks compared, ([\d,]+) differ", text)
    target = dimension or "minecraft:overworld"
    status = re.search(re.escape(target) + r": ([^\n]+)", output)
    errors = [line for line in text.splitlines() if "/ERROR]" in line or "/FATAL]" in line]
    errors = [line for line in errors if "MonsterRoomFeature" not in line]
    if not text:
        verdict = "server did not start"
    elif not finished:
        verdict = "did not finish generating"
    elif finished.group(4):
        verdict = "generated with failed chunks"
    elif check and check.group(2) != "0":
        verdict = f"runs; GPU differs from vanilla ({check.group(2)} of {check.group(1)} chunks)"
    elif check and check.group(1) != "0":
        verdict = f"runs; GPU identical to vanilla ({check.group(1)} chunks compared)"
    else:
        verdict = "runs; GPU not used for this generator"
    detail = (status.group(1).strip() if status else "")[:150]
    if errors:
        detail += f" | {len(errors)} error lines, first: " + re.sub(r"^\[[^\]]*\] \[[^\]]*\] ", "", errors[0])[:140]
    results.append((group, verdict, detail, names))


def main():
    wanted = sys.argv[1:] or list(GROUPS)
    results = []
    for group in wanted:
        slugs, dimension, radius = GROUPS[group]
        print(f"== {group}", flush=True)
        run(group, slugs, dimension, radius, results)
        print("   " + results[-1][1] + (" -- " + results[-1][2] if results[-1][2] else ""), flush=True)
    lines = ["| Mods | Result | Detail | Files |", "| --- | --- | --- | --- |"]
    lines += [f"| {g} | {v} | {d} | {n} |" for g, v, d, n in results]
    out = ROOT / "build" / "compat" / "results.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"written {out}")


if __name__ == "__main__":
    main()
