// SPDX-License-Identifier: MIT
package dev.worldgennext.neoforge.command;

import dev.worldgennext.neoforge.WorldgenNextMod;
import dev.worldgennext.neoforge.compat.DistantHorizonsBridge;
import dev.worldgennext.neoforge.config.UserSettings;
import dev.worldgennext.neoforge.fast.FastNoiseEngine;
import dev.worldgennext.neoforge.pregen.Pregenerator;
import dev.worldgennext.neoforge.threading.GroupCommit;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.dedicated.DedicatedServer;
import net.neoforged.fml.ModList;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/** What the mod is doing, in words a server owner can act on.  Shown by /worldgennext status and at startup. */
public final class StatusReport {
    private StatusReport() {}

    public static List<String> lines(MinecraftServer server) {
        UserSettings settings = UserSettings.get();
        List<String> lines = new ArrayList<>();
        lines.add("WorldgenNext " + WorldgenNextMod.VERSION);
        if (!settings.enabled()) {
            lines.add("Disabled (enabled = false in " + settings.file() + "): chunks generate and save as without the mod.");
            return lines;
        }

        String device = FastNoiseEngine.deviceName();
        if (FastNoiseEngine.MODE == FastNoiseEngine.GpuMode.OFF) {
            lines.add("GPU: off (gpu.mode). CPU-side optimizations are active.");
        } else if (device != null) {
            lines.add("GPU: " + device + " (mode " + (FastNoiseEngine.CHECK ? "check" : FastNoiseEngine.MODE.name().toLowerCase(Locale.ROOT)) + ")");
        } else if (FastNoiseEngine.unavailableReason() != null) {
            lines.add("GPU: not available, terrain generates on the CPU. Reason: " + FastNoiseEngine.unavailableReason());
        } else {
            lines.add("GPU: not started yet");
        }
        for (FastNoiseEngine.DimensionStatus dimension : FastNoiseEngine.dimensions()) {
            String what;
            if (!dimension.terrain()) {
                what = dimension.detail();
            } else if (FastNoiseEngine.CHECK) {
                what = "vanilla generation; the GPU's " + (dimension.surface() ? "terrain and surface" : "terrain") + " is compared with it";
            } else {
                what = (dimension.surface() ? "terrain and surface on the GPU" : "terrain on the GPU, surface on the CPU")
                        + " (" + dimension.detail() + ")";
            }
            lines.add("  " + dimension.dimension() + ": " + what);
        }
        FastNoiseEngine.Counters counters = FastNoiseEngine.counters();
        if (!FastNoiseEngine.CHECK && (device != null || counters.gpu() > 0)) {
            lines.add(String.format(Locale.ROOT, "Chunks since start: %,d on the GPU, %,d on the CPU, %,d redone on the CPU after a GPU bail-out",
                    counters.gpu(), counters.cpuFallback(), counters.bail()));
        }
        if (FastNoiseEngine.CHECK) {
            lines.add(String.format(Locale.ROOT, "Check mode: chunks are generated by vanilla code and the GPU's result is compared with it."
                    + " %,d chunks compared, %,d differ.", counters.checked(), counters.differing()));
            if (counters.differing() > 0) {
                lines.add("  The GPU does not reproduce this world generator. Keep gpu.mode = \"auto\" or \"off\"; the log lists the first differences.");
            } else if (counters.checked() >= 2000) {
                lines.add("  No differences so far. gpu.mode = \"force\" uses the GPU for this world; the more varied the terrain"
                        + " compared, the stronger this evidence.");
            } else {
                lines.add("  Generate at least a few thousand chunks across different biomes before relying on the result.");
            }
        }
        lines.add("Parallel generation steps: " + onOff(settings.parallelSteps()) + ". Background saving: "
                + (settings.asyncSaving() ? "on, compression level " + settings.compressionLevel() : "off") + ".");
        String distantHorizons = DistantHorizonsBridge.status();
        if (distantHorizons != null) lines.add(distantHorizons);
        String pregen = Pregenerator.status(server);
        if (pregen != null) lines.add("Pregeneration: " + pregen);

        if (!ModList.get().isLoaded("scalablelux")) {
            lines.add("Tip: ScalableLux is not installed. Lighting then runs on vanilla's single light thread; the published"
                    + " throughput figures were measured with ScalableLux.");
        }
        // Synchronous writes cost about 2% with group commit (measured over 90,601 chunks); only worth a tip without it.
        if (!GroupCommit.ENABLED && server.forceSynchronousWrites()) {
            lines.add("Tip: " + (server instanceof DedicatedServer ? "sync-chunk-writes=true in server.properties" : "syncChunkWrites:true in options.txt")
                    + " makes every chunk write wait for the disk, and group commit is switched off.");
        }
        for (String problem : settings.problems()) lines.add("Config: " + problem);
        lines.add("Config file: " + settings.file());
        return lines;
    }

    private static String onOff(boolean value) {
        return value ? "on" : "off";
    }
}
